apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gitops-git
  namespace: coffeeshop-pipelines
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.ibm.com/appsody-coffeeshop/gitops.git
